### ISSUE TITLE
Enabling with dblite.open() as ds syntax

### ISSUE THREAD

**Issue by Mrowqa** [ownport/scrapy-dblite#28]
Hi!

How about defining `__enter__` and `__exit__` methods for `Storage`? Then this would be possible:
```python
    with dblite.open(MyItem, 'sqlite://my.db:table') as ds:
        print('My items:', list(ds.get()))
```
Handling errors would be much easier.

**Comment by ownport** [comment]
Done. Please have look on latest commit 6bcdad5

**Comment by Mrowqa** [comment]
It looks great. Thanks :)
