### ISSUE TITLE
Error in example in pypi page

### ISSUE THREAD

**Issue by willbeaufoy** [ownport/scrapy-dblite#29]
In the 'Using dblite in Item Pipeline' example [on pypi](https://pypi.python.org/pypi/scrapy-dblite/0.2.5) this line:

`self.ds = open(Product, 'sqlite://db/products.sqlite:items', autocommit=True)`

should read:

`self.ds = dblite.open(Product, 'sqlite://db/products.sqlite:items', autocommit=True)`

It's correct on the [github version](https://github.com/ownport/scrapy-dblite) of this example

**Comment by ownport** [comment]
Update in the version scrapy-dblite 0.2.7 https://pypi.python.org/pypi/scrapy-dblite/0.2.7
